In [1]:
import csv
import pandas as pd
from pathlib import Path

In [2]:
csv_activity = Path("Resources/FitBitStudy/dailyActivity_merged.csv")
csv_sleep = Path("Resources/FitBitStudy/sleepDay_merged.csv")
csv_stress = Path("Resources/Stress_Health_Study/Sleep_health_and_lifestyle_dataset.csv")

In [3]:
csv_reader_activity = pd.read_csv(csv_activity)
csv_reader_sleep = pd.read_csv(csv_sleep)
csv_reader_stress = pd.read_csv(csv_stress)

In [40]:
csv_reader_activity.head(10)

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863
5,1503960366,4/17/2016,9705,6.48,6.48,0.0,3.19,0.78,2.51,0.0,38,20,164,539,1728
6,1503960366,4/18/2016,13019,8.59,8.59,0.0,3.25,0.64,4.71,0.0,42,16,233,1149,1921
7,1503960366,4/19/2016,15506,9.88,9.88,0.0,3.53,1.32,5.03,0.0,50,31,264,775,2035
8,1503960366,4/20/2016,10544,6.68,6.68,0.0,1.96,0.48,4.24,0.0,28,12,205,818,1786
9,1503960366,4/21/2016,9819,6.34,6.34,0.0,1.34,0.35,4.65,0.0,19,8,211,838,1775

In [41]:
csv_reader_sleep.head(10)

,Id,SleepDay,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016,1,327,346
1,1503960366,4/13/2016,2,384,407
2,1503960366,4/15/2016,1,412,442
3,1503960366,4/16/2016,2,340,367
4,1503960366,4/17/2016,1,700,712
5,1503960366,4/19/2016,1,304,320
6,1503960366,4/20/2016,1,360,377
7,1503960366,4/21/2016,1,325,364
8,1503960366,4/23/2016,1,361,384
9,1503960366,4/24/2016,1,430,449

In [42]:
csv_reader_sleep = csv_reader_sleep.rename(columns={"SleepDay" : "ActivityDate"})
csv_reader_sleep.head(10)

,Id,ActivityDate,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016,1,327,346
1,1503960366,4/13/2016,2,384,407
2,1503960366,4/15/2016,1,412,442
3,1503960366,4/16/2016,2,340,367
4,1503960366,4/17/2016,1,700,712
5,1503960366,4/19/2016,1,304,320
6,1503960366,4/20/2016,1,360,377
7,1503960366,4/21/2016,1,325,364
8,1503960366,4/23/2016,1,361,384
9,1503960366,4/24/2016,1,430,449

In [ ]:
#merged_df = pd.merge(csv_reader_activity, csv_reader_sleep, on=["Id", "ActivityDate"], how="outer")
#merged_df.head(60)

In [43]:
merged_df = pd.merge(csv_reader_activity, csv_reader_sleep, on=["Id", "ActivityDate"])
merged_df.head(60)

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,TotalSleepRecords,TotalMinutesAsleep,TotalTimeInBed
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985,1,327,346
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797,2,384,407
2,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745,1,412,442
3,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863,2,340,367
4,1503960366,4/17/2016,9705,6.48,6.48,0.0,3.19,0.78,2.51,0.0,38,20,164,539,1728,1,700,712
5,1503960366,4/19/2016,15506,9.88,9.88,0.0,3.53,1.32,5.03,0.0,50,31,264,775,2035,1,304,320
6,1503960366,4/20/2016,10544,6.68,6.68,0.0,1.96,0.48,4.24,0.0,28,12,205,818,1786,1,360,377
7,1503960366,4/21/2016,9819,6.34,6.34,0.0,1.34,0.35,4.65,0.0,19,8,211,838,1775,1,325,364
8,1503960366,4/23/2016,14371,9.04,9.04,0.0,2.81,0.87,5.36,0.0,41,21,262,732,1949,1,361,384
9,1503960366,4/24/2016,10039,6.41,6.41,0.0,2.92,0.21,3.28,0.0,39,5,238,709,1788,1,430,449
10,1503960366,4/25/2016,15355,9.80,9.80,0.0,5.29,0.57,3.94,0.0,73,14,216,814,2013,1,277,323
11,1503960366,4/26/2016,13755,8.79,8.79,0.0,2.33,0.92,5.54,0.0,31,23,279,833,1970,1,245,274
12,1503960366,4/28/2016,13154,8.53,8.53,0.0,3.54,1.16,3.79,0.0,48,28,189,782,1898,1,366,393
13,1503960366,4/29/2016,11181,7.15,7.15,0.0,1.06,0.50,5.58,0.0,16,12,243,815,1837,1,341,354
14,1503960366,4/30/2016,14673,9.25,9.25,0.0,3.56,1.42,4.27,0.0,52,34,217,712,1947,1,404,425
15,1503960366,5/1/2016,10602,6.81,6.81,0.0,2.29,1.60,2.92,0.0,33,35,246,730,1820,1,369,396
16,1503960366,5/2/2016,14727,9.71,9.71,0.0,3.21,0.57,5.92,0.0,41,15,277,798,2004,1,277,309
17,1503960366,5/3/2016,15103,9.66,9.66,0.0,3.73,1.05,4.88,0.0,50,24,254,816,1990,1,273,296
18,1503960366,5/5/2016,14070,8.90,8.90,0.0,2.92,1.08,4.88,0.0,45,24,250,857,1959,1,247,264
19,1503960366,5/6/2016,12159,8.03,8.03,0.0,1.97,0.25,5.81,0.0,24,6,289,754,1896,1,334,367
20,1503960366,5/7/2016,11992,7.71,7.71,0.0,2.46,2.12,3.13,0.0,37,46,175,833,1821,1,331,349
21,1503960366,5/8/2016,10060,6.58,6.58,0.0,3.53,0.32,2.73,0.0,44,8,203,574,1740,1,594,611
22,1503960366,5/9/2016,12022,7.72,7.72,0.0,3.45,0.53,3.74,0.0,46,11,206,835,1819,1,338,342
23,1503960366,5/10/2016,12207,7.77,7.77,0.0,3.35,1.16,3.26,0.0,46,31,214,746,1859,1,383,403
24,1503960366,5/11/2016,12770,8.13,8.13,0.0,2.56,1.01,4.55,0.0,36,23,251,669,1783,1,285,306
25,1644430081,4/29/2016,3176,2.31,2.31,0.0,0.00,0.00,2.31,0.0,0,0,120,1193,2498,1,119,127
26,1644430081,4/30/2016,18213,13.24,13.24,0.0,0.63,3.14,9.46,0.0,9,71,402,816,3846,1,124,142
27,1644430081,5/2/2016,3758,2.73,2.73,0.0,0.07,0.31,2.35,0.0,1,7,148,682,2580,1,796,961
28,1644430081,5/8/2016,6724,4.89,4.89,0.0,0.00,0.00,4.88,0.0,0,0,295,991,2987,1,137,154
29,1844505072,4/15/2016,3844,2.54,2.54,0.0,0.00,0.00,2.54,0.0,0,0,176,527,1725,1,644,961
30,1844505072,4/30/2016,4014,2.67,2.67,0.0,0.00,0.00,2.65,0.0,0,0,184,218,1763,1,722,961
31,1844505072,5/1/2016,2573,1.70,1.70,0.0,0.00,0.26,1.45,0.0,0,7,75,585,1541,1,590,961
32,1927972279,4/12/2016,678,0.47,0.47,0.0,0.00,0.00,0.47,0.0,0,0,55,734,2220,3,750,775
33,1927972279,4/13/2016,356,0.25,0.25,0.0,0.00,0.00,0.25,0.0,0,0,32,986,2151,1,398,422
34,1927972279,4/15/2016,980,0.68,0.68,0.0,0.00,0.00,0.68,0.0,0,0,51,941,2221,2,475,499
35,1927972279,4/26/2016,3761,2.60,2.60,0.0,0.00,0.00,2.60,0.0,0,0,192,1058,2638,1,296,315
36,1927972279,4/28/2016,1675,1.16,1.16,0.0,0.00,0.00,1.16,0.0,0,0,95,1167,2351,1,166,178
37,2026352035,4/12/2016,4414,2.74,2.74,0.0,0.19,0.35,2.20,0.0,3,8,181,706,1459,1,503,546
38,2026352035,4/13/2016,4993,3.10,3.10,0.0,0.00,0.00,3.10,0.0,0,0,238,663,1521,1,531,565
39,2026352035,4/14/2016,3335,2.07,2.07,0.0,0.00,0.00,2.05,0.0,0,0,197,653,1431,1,545,568
40,2026352035,4/15/2016,3821,2.37,2.37,0.0,0.00,0.00,2.37,0.0,0,0,188,687,1444,1,523,573
41,2026352035,4/16/2016,2547,1.58,1.58,0.0,0.00,0.00,1.58,0.0,0,0,150,728,1373,1,524,567
42,2026352035,4/17/2016,838,0.52,0.52,0.0,0.00,0.00,0.52,0.0,0,0,60,1053,1214,1,437,498
43,2026352035,4/19/2016,2424,1.50,1.50,0.0,0.00,0.00,1.50,0.0,0,0,141,785,1356,1,498,540
44,2026352035,4/20/2016,7222,4.48,4.48,0.0,0.00,0.00,4.48,0.0,0,0,327,623,1667,1,461,510
45,2026352035,4/21/2016,2467,1.53,1.53,0.0,0.00,0.00,1.53,0.0,0,0,153,749,1370,1,477,514
46,2026352035,4/22/2016,2915,1.81,1.81,0.0,0.00,0.00,1.81,0.0,0,0,162,712,1399,1,520,545
47,2026352035,4/23/2016,12357,7.71,7.71,0.0,0.00,0.00,7.71,0.0,0,0,432,458,1916,1,522,554
48,2026352035,4/24/2016,3490,2.16,2.16,0.0,0.00,0.00,2.16,0.0,0,0,164,704,1401,1,555,591
49,2026352035,4/25/2016,6017,3.73,3.73,0.0,0.00,0.00,3.73,0.0,0,0,260,821,1576,1,506,531
50,2026352035,4/27/2016,6088,3.77,3.77,0.0,0.00,0.00,3.77,0.0,0,0,286,586,1593,1,508,545
51,2026352035,4/28/2016,6375,3.95,3.95,0.0,0.00,0.00,3.95,0.0,0,0,331,626,1649,1,513,545
52,2026352035,4/29/2016,7604,4.71,4.71,0.0,0.00,0.00,4.71,0.0,0,0,352,492,1692,1,490,510
53,2026352035,4/30/2016,4729,2.93,2.93,0.0,0.00,0.00,2.93,0.0,0,0,233,594,1506,1,573,607
54,2026352035,5/1/2016,3609,2.28,2.28,0.0,0.00,0.00,2.28,0.0,0,0,191,716,1447,1,527,546
55,2026352035,5/2/2016,7018,4.35,4.35,0.0,0.00,0.00,4.35,0.0,0,0,355,716,1690,1,511,543
56,2026352035,5/4/2016,6564,4.07,4.07,0.0,0.00,0.00,4.07,0.0,0,0,345,530,1658,1,538,560
57,2026352035,5/5/2016,12167,7.54,7.54,0.0,0.00,0.00,7.54,0.0,0,0,475,479,1926,1,468,485
58,2026352035,5/6/2016,8198,5.08,5.08,0.0,0.00,0.00,5.08,0.0,0,0,383,511,1736,1,524,548
59,2026352035,5/7/2016,4193,2.60,2.60,0.0,0.00,0.00,2.60,0.0,0,0,229,665,1491,1,511,521

In [44]:
merged_df.shape

(413, 18)

In [45]:
merged_df[merged_df["TotalMinutesAsleep"].isnull()].shape

(0, 18)

In [ ]:
#merged_df.to_csv()